# Generated by Django 3.2.8 on 2021-10-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='kelompok_id',
        ),
        migrations.AddField(
            model_name='buku',
            name='nopustaka',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
